-   id: dprint
    name: dprint
    entry: dprint fmt
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["dprint@0.7.0"]
    minimum_pre_commit_version: '0'
