-   id: dprint
    name: dprint
    description: 'A pluggable and configurable code formatting platform written in Rust.'
    entry: echo $PWD >&2 
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["dprint@0.36.1"]
    minimum_pre_commit_version: '0'
    pass_filenames: false # https://github.com/adamchainz/pre-commit-dprint/issues/3#issuecomment-1483410008
